version: '3'
services:
  app:
    build: .
    image: caredoc
    container_name: caredoc_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/caredoc
    volumes:
      - .:/var/www/caredoc
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - caredoc

  webserver:
    image: nginx:alpine
    container_name: nginxcaredoc
    restart: unless-stopped
    tty: true
    ports:
      - "2022:80"
    volumes:
      - .:/var/www/caredoc
      - ./storage/:/etc/nginx/conf.d/
    networks:
      - caredoc

  db:
    image: mysql:5.7
    container_name: dbcaredoc
    restart: always
    tty: true
    ports:
      - "2023:3306"
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: caredoc
      MYSQL_ROOT_PASSWORD: caredoc
      MYSQL_DATABASE: caredoc-local
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - caredoc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmacaredoc
    links:
      - db
    restart: always
    ports:
      - "7000:80"
    networks:
      - caredoc

#NETWORK
networks:
  caredoc:
    driver: bridge

#VOLUMES
volumes:
  lbdata:
    driver: local